openapi: 3.0.1
info:
  title: Hello World
  version: v0
servers:
  - url: http://localhost:3000
    description: Server URL
paths:
  /helloworld:
    get:
      tags:
        - Basic
        - HelloWorld
      operationId: helloworld
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  hello:
                    type: string
              example:
                hello: world