openapi: 3.0.1
info:
  title: Hello World
  version: v0
servers:
  - url: http://localhost:3000
    description: Server URL
paths:
  /helloworld:
    get:
      tags:
        - Basic
        - HelloWorld
        - GET
      operationId: helloworldget
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  hello:
                    type: string
              example:
                hello: world! as a GET request
    post:
      tags:
        - Basic
        - HelloWorld
        - POST
      operationId: helloworldpost
      requestBody:
          content:
            application/json:
              schema:
                properties:
                  hello:
                    type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  hello:
                    type: string
              example:
                hello: world!
                data: /{data}/

    put:
      tags:
        - Basic
        - HelloWorld
        - PUT
      operationId: helloworldput
      requestBody:
          content:
            application/json:
              schema:
                properties:
                  hello:
                    type: string
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  hello:
                    type: string
              example:
                hello: world! as a PUT request
    delete:
      tags:
        - Basic
        - HelloWorld
        - DELETE
      operationId: helloworlddelete
      responses:
        '200':
          description: OK
          content:
            'application/json':
              schema:
                properties:
                  hello:
                    type: string
              example:
                hello: world! as a DELETE request